name: toa_flutter
description: An app for accessing data about the FIRST Tech Challenge.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 2.2.0+15

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  http: ^0.12.2
  shared_preferences: ^0.5.12+4
  flutter_sticky_header: ^0.5.0
  intl: ^0.16.1
  cupertino_icons: ^0.1.2
  material_design_icons_flutter: ^4.0.5755
  url_launcher: ^5.7.10
  add_2_calendar: ^1.4.0
  dynamic_theme: ^1.0.1
  rounded_modal: ^1.0.0
  rect_getter: ^0.1.0
  device_info: ^1.0.0
  package_info: ^0.4.3+2

  # Firebase
  firebase_core: ^0.5.2
  firebase_auth: ^0.18.3
  firebase_storage: ^5.0.1
  firebase_analytics: ^6.2.0
  firebase_messaging: ^7.0.3

  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

# The following section is specific to Flutter.
flutter:
  # Material Icons Font.
  uses-material-design: true
  assets:
    - assets/images/event.jpg
    - assets/images/loading.gif
    - assets/lang/en.json
    - assets/lang/he.json
  fonts:
    - family: TOA Icons
      fonts:
        - asset: assets/fonts/TOAIcons.ttf

    - family: GoogleSans
      fonts:
        - asset: assets/fonts/GoogleSans-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/GoogleSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/GoogleSans-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/GoogleSans-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/GoogleSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/GoogleSans-Regular.ttf
          weight: 400
